/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hibernate.basic;

import java.util.Arrays;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;


public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//     	System.out.println(new App().getGreeting());
      
    	Student temp = new Student();
    	temp.setId(10);
    	temp.setName("Ten TEn");
    	
    	Laptop l1 = new Laptop();
		l1.setL_name("Dell");
		l1.setL_id(1011);
		l1.setStudent(temp);
		
		Laptop l2 = new Laptop();
		l2.setL_name("HP");
		l2.setL_id(2011);
		l2.setStudent(temp);
		
		List<Laptop> lps = Arrays.asList(l1,l2);
		
		temp.setLaptop(lps);
    
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class).addAnnotatedClass(Laptop.class);
    	
    	SessionFactory sf = con.buildSessionFactory();
    	
    	Session session = sf.openSession();
    	
    	Transaction ts = session.beginTransaction();
//    	session.beginTransaction();
    	
    	session.save(temp);
    	session.save(l1);
    	session.save(l2);
 
    	ts.commit();
//    	session.getTransaction().commit();
    	
    	session.close();
    	
    	System.out.println(temp);
    }
}
