/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hibernate.basic;

import java.util.Arrays;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.Query;




public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//     	System.out.println(new App().getGreeting());
   
    
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class).addAnnotatedClass(Laptop.class);
    	
    	SessionFactory sf = con.buildSessionFactory();
    	
    	Session session = sf.openSession();
    	
    	Transaction ts = session.beginTransaction();
//    	session.beginTransaction();
    	
    	//selection query
    	Query q = session.createQuery("from Student");
      
    	List<Student> p = q.list();
      
    	p.forEach(System.out::println);
    		System.out.println(p);
    		
    	//deletion query
//    	Query q1 = session.createQuery("delete from Student where id=1");
//    	q1.setParameter("1", 2);
//    	System.out.println(q1.executeUpdate());	
 
    	ts.commit();
//    	session.getTransaction().commit();
    	
    	session.close();
    	
    }
}
