/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hibernate.basic;

import java.util.Arrays;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.NativeQuery;



public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//     	System.out.println(new App().getGreeting());
   
    
    	Configuration con = new Configuration().configure().addAnnotatedClass(Student.class).addAnnotatedClass(Laptop.class);
    	
    	SessionFactory sf = con.buildSessionFactory();
    	
    	Session session = sf.openSession();
    	
    	Transaction ts = session.beginTransaction();
//    	session.beginTransaction();
    	
    	NativeQuery q4 = session.createSQLQuery("select * from student");
        
        List<Object[]> ob1 = q4.list();
        
        for (Object[] o: ob1) {
        	
        	System.out.println(o[0]+" : "+o[1]+" : "+o[2]);
        }
 
    	ts.commit();
//    	session.getTransaction().commit();
    	
    	session.close();
    	
    }
}
