/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JPA.DEMO;

import java.util.Arrays;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
    
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("student");
 	   	EntityManager em = emf.createEntityManager();
 	   
	   	em.getTransaction().begin();
	   	
	   
    	Student s1 = new Student();
 	   	s1.setName("One");
 	   	Student s2 = new Student();
	   	s2.setName("Two");
	   	Student s3 = new Student();
 	   	s3.setName("Three");
 	   
 	   	Laptop laptop1 = new Laptop();
  		laptop1.setL_id(1);
  		laptop1.setL_name("Dell");
  	
      	Laptop laptop2 = new Laptop();
      	laptop2.setL_id(2);
      	laptop2.setL_name("HP");
      	
      	List<Laptop> lps = Arrays.asList(laptop1,laptop2);
	   	
      	s1.setLaptop(lps);
      	s2.setLaptop(lps);
      	s3.setLaptop(lps);
      
      	
 	   	em.merge(s1);
 	   	em.merge(s2);
 	   	em.merge(s3);
 	   	
 	   Query query = em.createQuery("from Student");

	   List<Student> names = query.getResultList();
	   names.forEach(System.out::println);
 	   	
	   em.getTransaction().commit();
	   
	   em.close();
	   emf.close();
    }
}
